#!/usr/bin/env sh

case $(uname -s) in
    Linux*)
        if [ -x /usr/bin/dircolors ]; then
            test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"

            alias ls="ls --color=auto"
            alias dir="dir --color=auto"
            alias vdir="vdir --color=auto"

            alias grep="grep --color=auto"
            alias fgrep="fgrep --color=auto"
            alias egrep="egrep --color=auto"
        fi
        ;;
    Darwin*)
        alias ls="ls -FG"
        alias flush="dscacheutil -flushcache"
        ;;
esac

# Navigation
alias ..="cd .."
alias ...="cd ../.."

alias ll="ls -la"

# Text-mangling
alias tawk="awk -v FS='\t' -v OFS='\t'"

alias w2u="iconv -f cp1251 -t utf-8"
alias u2w="iconv -f utf-8 -t cp1251"

# Dumb shortcuts
alias v="vim"
alias fs="stat -f '%z bytes'"

# Smart shortcuts
alias realpath="python -c 'import os, sys; print os.path.realpath(sys.argv[1])' $@"
alias rmorig="find . -name '*.orig' -delete"
alias rmbom="perl -CD -pe 'tr/\x{feff}//d'"

# git
alias g="git"

alias ga="git add"
alias gai="git add --interactive"

alias gb="git branch"
alias gba="git branch -a"

alias gc="git commit"

alias gco="git checkout"

alias gd="git diff"
alias gdc="git diff --cached"

alias gs="git status"
alias gst="git status"

alias glg="git log-graph"
alias gLg="git log-short"
alias gll="git --no-pager log-graph -5 && echo"
alias gLL="git --no-pager log-short -5 && echo"

alias gl="git pull --rebase"
alias gp="git push"

alias grr="git reset HEAD . ; git checkout ."

alias gsu="git submodule update --init --recursive"

# tmux
refresh_tmux() {
    if [[ -n $TMUX ]]; then
        NEW_SSH_AUTH_SOCK=`tmux showenv | grep ^SSH_AUTH_SOCK | cut -d = -f 2`
        if [[ -n $NEW_SSH_AUTH_SOCK ]] && [[ -S $NEW_SSH_AUTH_SOCK ]]; then
            SSH_AUTH_SOCK=$NEW_SSH_AUTH_SOCK
            export SSH_AUTH_SOCK
        fi
        DISPLAY=`tmux showenv | grep ^DISPLAY | cut -d = -f 2`
        export DISPLAY
    fi
}

# *sh
alias reload='exec "$SHELL" -l'
